# Alertmanager configuration for CashAppAgent
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cashapp.com'
  smtp_auth_username: 'alerts@cashapp.com'
  smtp_auth_password: 'password'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: critical-alerts
    group_wait: 5s
    repeat_interval: 30m
    
  - match:
      severity: warning
    receiver: warning-alerts
    group_wait: 10s
    repeat_interval: 1h
    
  - match:
      team: platform
    receiver: platform-team
    
  - match:
      team: business
    receiver: business-team
    
  - match:
      team: ai
    receiver: ai-team

# Notification receivers
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'critical-alerts@cashapp.com'
    subject: '[CRITICAL] CashApp Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ .CommonAnnotations.summary }}
      Description: {{ .CommonAnnotations.description }}
      Details:
      {{ range .Alerts }}
      - Alert: {{ .Annotations.summary }}
        Started: {{ .StartsAt }}
        Labels: {{ .Labels }}
      {{ end }}
    send_resolved: true
  
  slack_configs:
  - api_url: '${SLACK_API_URL}'
    channel: '#alerts-critical'
    title: '[CRITICAL] CashApp Alert'
    text: '{{ .CommonAnnotations.summary }}'
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'alerts@cashapp.com'
    subject: '[WARNING] CashApp Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ .CommonAnnotations.summary }}
      Description: {{ .CommonAnnotations.description }}
    send_resolved: true

- name: 'platform-team'
  slack_configs:
  - api_url: '${SLACK_API_URL}'
    channel: '#platform-alerts'
    title: 'Platform Alert'
    text: '{{ .CommonAnnotations.summary }}'
    send_resolved: true

- name: 'business-team'
  email_configs:
  - to: 'business-team@cashapp.com'
    subject: 'Business Alert - CashApp'
    body: |
      Business Impact Alert:
      {{ .CommonAnnotations.summary }}
      
      Please review the business metrics dashboard.
    send_resolved: true

- name: 'ai-team'
  slack_configs:
  - api_url: '${SLACK_API_URL}'
    channel: '#ai-alerts'
    title: 'AI/ML Alert'
    text: '{{ .CommonAnnotations.summary }}'
    send_resolved: true

# Inhibition rules
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

- source_match:
    alertname: 'ServiceDown'
  target_match_re:
    alertname: '(HighErrorRate|HighResponseTime|QueueDepthHigh)'
  equal: ['service']